// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3Iqx2JgX30YTCP1rnscO4nnToHxzz5L0',
    appId: '1:111371324889:web:53e7f9f5418718f3dbddc8',
    messagingSenderId: '111371324889',
    projectId: 'flutter-class-23',
    authDomain: 'flutter-class-23.firebaseapp.com',
    storageBucket: 'flutter-class-23.appspot.com',
    measurementId: 'G-WRXYWE0P2V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4F23k0rQjBbdTwEigCOhB18JpXEniGOk',
    appId: '1:111371324889:android:cb7be55b857e008edbddc8',
    messagingSenderId: '111371324889',
    projectId: 'flutter-class-23',
    storageBucket: 'flutter-class-23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ0oA3WHwHqKA1EqnX8PcLad3xE5JtabA',
    appId: '1:111371324889:ios:fa369c379626e44fdbddc8',
    messagingSenderId: '111371324889',
    projectId: 'flutter-class-23',
    storageBucket: 'flutter-class-23.appspot.com',
    iosBundleId: 'com.example.flutterClass23',
  );
}
